url: "https://status.flus.io/"
uuid: "bf32d1b1-1d9e-5e6b-9f2f-c34466ac65e3"
title: "Statut de flus.io"
author: "Marien"
timezone: "Europe/Paris"
force_feed: true
blog_slug: "index"
app_status: "up"
websub_hub: "https://websub.flus.io/"

development:
    url: "filesystem"
